update ci_for_ui_tests.yml

diff --git a/.github/workflows/ci_for_ui_tests.yml b/.github/workflows/ci_for_ui_tests.yml
--- a/.github/workflows/ci_for_ui_tests.yml
+++ b/.github/workflows/ci_for_ui_tests.yml
@@ -29,13 +29,19 @@ jobs:
     - name: Install compatible ChromeDriver
       run: |
         CHROME_VERSION=${{ steps.chrome_version.outputs.CHROME_VERSION }}
+        # Fetches the latest release of the specified major Chrome version
         CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
-        wget -N "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
-        unzip ~/chromedriver_linux64.zip -d ~/
-        sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
-        sudo chown root:root /usr/local/bin/chromedriver
-        sudo chmod 0755 /usr/local/bin/chromedriver
-        chromedriver --version
+        if [ ! -z "$CHROMEDRIVER_VERSION" ]; then
+          wget -N "http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -P ~/
+          unzip ~/chromedriver_linux64.zip -d ~/
+          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
+          sudo chown root:root /usr/local/bin/chromedriver
+          sudo chmod 0755 /usr/local/bin/chromedriver
+          chromedriver --version
+        else
+          echo "Failed to find ChromeDriver for Chrome version $CHROME_VERSION"
+          exit 1
+        fi
 
     - name: Install dependencies
       run: |
